# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# add space
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# max width indent
Layout/IndentationWidth:
  Width: 2

Layout/IndentationStyle:
  EnforcedStyle: spaces

# change single quotes to double quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes
